# Generated by Django 5.0.6 on 2024-12-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companydetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='user',
        ),
    ]
