# Generated by Django 5.0.6 on 2024-12-05 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpWorkDetails',
            fields=[
                ('wdId', models.AutoField(primary_key=True, serialize=False)),
                ('empId', models.CharField(max_length=255, unique=True)),
                ('employmentStatus', models.CharField(max_length=100)),
                ('companyEmailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('dateOfJoining', models.DateField(blank=True, default=None, null=True)),
                ('dateOfRelieving', models.DateField(blank=True, default=None, null=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('roleType', models.CharField(blank=True, max_length=100, null=True)),
                ('currentRole', models.CharField(max_length=100)),
                ('reportingManager', models.CharField(max_length=100)),
                ('reasonForLeaving', models.TextField(blank=True, null=True)),
                ('monthYearOfTermination', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExpInThisCompany', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExperience', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExpBeforeJoining', models.CharField(blank=True, max_length=100, null=True)),
                ('previousDateOfJoining', models.DateField(blank=True, default=None, null=True)),
                ('previousEmployer', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.companydetails')),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeesrole', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpSocialSecurityDetails',
            fields=[
                ('ssdId', models.AutoField(primary_key=True, serialize=False)),
                ('panNum', models.CharField(blank=True, max_length=20, null=True)),
                ('uanNum', models.CharField(blank=True, max_length=20, null=True)),
                ('aadharNum', models.CharField(blank=True, max_length=20, null=True)),
                ('bankName', models.CharField(blank=True, max_length=100, null=True)),
                ('ifscCode', models.CharField(blank=True, max_length=20, null=True)),
                ('bankAccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('wdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalaryDetails',
            fields=[
                ('sdId', models.AutoField(primary_key=True, serialize=False)),
                ('CTCpayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BasicpayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DApayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('HRApayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AdvancesAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('VariableAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('QAllowanceAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('QBonusAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ABonusAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SAllowancesAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PTAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PFAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ESIAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DLoansAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('VPFAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reimbursements', models.JSONField(default=dict)),
                ('pf_type', models.CharField(blank=True, choices=[('!=15k', 'No Limit for PF Deduction'), ('15k', 'Wage limit 15k')], max_length=10, null=True)),
                ('wdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpPersonalDetails',
            fields=[
                ('pdId', models.AutoField(primary_key=True, serialize=False)),
                ('personalEmailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('educationalQualification', models.CharField(blank=True, max_length=100, null=True)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('marriageDate', models.DateField(blank=True, null=True)),
                ('currentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('generalContact', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('relationshipName', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=10, null=True)),
                ('shirtSize', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('wdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpInsuranceDetails',
            fields=[
                ('isdId', models.AutoField(primary_key=True, serialize=False)),
                ('fathersName', models.CharField(blank=True, max_length=100, null=True)),
                ('fathersDOB', models.DateField(blank=True, null=True)),
                ('mothersName', models.CharField(blank=True, max_length=100, null=True)),
                ('mothersDOB', models.DateField(blank=True, null=True)),
                ('spouseName', models.CharField(blank=True, max_length=100, null=True)),
                ('spouseDOB', models.DateField(blank=True, null=True)),
                ('child1', models.CharField(blank=True, max_length=100, null=True)),
                ('child1DOB', models.DateField(blank=True, null=True)),
                ('child2', models.CharField(blank=True, max_length=100, null=True)),
                ('child2DOB', models.DateField(blank=True, null=True)),
                ('wdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
    ]
