# Generated by Django 5.0.6 on 2024-12-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_login_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_superuser',
        ),
    ]
