# Generated by Django 5.0.6 on 2024-12-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_login_company'),
        ('company', '0004_companydetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydetails', to='company.companydetails'),
        ),
    ]
