# Generated by Django 5.0.6 on 2024-12-05 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('companyRegisteredId', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('adminName', models.CharField(max_length=255)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPhoneNum', models.CharField(max_length=15)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('tan', models.CharField(blank=True, max_length=10, null=True)),
                ('coi', models.ImageField(blank=True, null=True, upload_to='coi/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('leavePolicy', models.FileField(blank=True, null=True, upload_to='leave_policies/')),
                ('pfPolicy', models.FileField(blank=True, null=True, upload_to='pf_policies/')),
                ('labourLawLicence', models.FileField(blank=True, null=True, upload_to='labour_law_policies/')),
                ('isCompanyDetailsCompleted', models.BooleanField(default=False)),
                ('payrollDone', models.BooleanField(default=False)),
                ('employeeSetupDone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
