# Generated by Django 5.0.6 on 2024-12-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('ecId', models.AutoField(primary_key=True, serialize=False)),
                ('basic_percentage', models.FloatField()),
                ('hra_enabled', models.BooleanField(default=False)),
                ('hra_percentage', models.FloatField(blank=True, null=True)),
                ('da_enabled', models.BooleanField(default=False)),
                ('da_percentage', models.FloatField(blank=True, null=True)),
                ('reimbursements', models.JSONField(default=dict)),
                ('advances', models.BooleanField(default=False)),
                ('variable_pay', models.BooleanField(default=False)),
                ('deductions', models.BooleanField(default=False)),
                ('quarterly_allowance', models.BooleanField(default=False)),
                ('quarterly_bonus', models.BooleanField(default=False)),
                ('annual_bonus', models.BooleanField(default=False)),
                ('special_allowances', models.BooleanField(default=False)),
                ('professional_tax', models.BooleanField(default=False)),
                ('esi', models.BooleanField(default=False)),
                ('pf', models.BooleanField(default=False)),
                ('pf_type', models.CharField(blank=True, choices=[('!=15k', 'No Limit for PF Deduction'), ('15k', 'Wage limit 15k'), ('Both', 'Both Options')], max_length=10, null=True)),
                ('voluntary_pf', models.BooleanField(default=False, null=True)),
                ('is_payroll_generated', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='company.companydetails')),
            ],
        ),
    ]
