# Generated by Django 5.0.6 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_empworkdetails_employmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkdetails',
            name='employmentType',
            field=models.CharField(max_length=100),
        ),
    ]
